const ADD_CONTACT = "ADD_CONTACT"
const REMOVE_CONTACT = "REMOVE_CONTACT"
const FETCH_CONTACTS = "FETCH_CONTACTS"
const DATABASE_SAVING = "DATABASE_SAVING"
const DATABASE_INSPECTING = "DATABASE_INSPECTING"
const ERROR = "ERROR"
const LOADING_DATA = "LOADING_DATA"
const SET_CURRENT = "SET_CURRENT"

export {ADD_CONTACT, 
    REMOVE_CONTACT, 
    FETCH_CONTACTS,
    SET_CURRENT, 
    DATABASE_INSPECTING, 
    LOADING_DATA, 
    DATABASE_SAVING, 
    ERROR}