const ADD_CONTACT = "ADD_CONTACT"
const ADD_USER = "ADD_USER"
const FETCH_USERS = "FETCH_USERS"
const REMOVE_CONTACT = "REMOVE_CONTACT"
const FETCH_CONTACTS = "FETCH_CONTACTS"
const DATABASE_SAVING = "DATABASE_SAVING"
const DATABASE_INSPECTING = "DATABASE_INSPECTING"
const ERROR = "ERROR"
const LOADING_DATA = "LOADING_DATA"
const SET_CURRENT = "SET_CURRENT"

export {ADD_CONTACT,
    ADD_USER, 
    FETCH_USERS, 
    REMOVE_CONTACT, 
    FETCH_CONTACTS,
    SET_CURRENT, 
    DATABASE_INSPECTING, 
    LOADING_DATA, 
    DATABASE_SAVING, 
    ERROR}